# Generated by Django 3.2.3 on 2021-05-22 10:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AllocatedJobs',
            new_name='AllocatedJob',
        ),
    ]
