# Generated by Django 3.2.3 on 2021-05-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_allocatedjobs_allocatedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='microtask',
            name='is_allocated',
            field=models.BooleanField(default=False),
        ),
    ]
