# Generated by Django 3.2.3 on 2021-05-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_microtask_is_allocated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocatedjob',
            name='time_allocated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='allocatedjob',
            name='time_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
