# Generated by Django 3.2.3 on 2021-05-23 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20210522_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malrequirement',
            name='micro_task',
            field=models.ForeignKey(limit_choices_to={'is_selected': False}, on_delete=django.db.models.deletion.CASCADE, to='jobs.microtask'),
        ),
    ]
